#!/bin/bash

# First argument is the target machine
# Second argument is the action (up or down)
TARGET=$1
ACTION=$2

while read line; do
  name=`echo $line | cut -d' ' -f1`
  address=`echo $line | cut -d' ' -f2`
  if [ "$name" = "$TARGET" ]; then
    scp "$name/docker-compose.yml" "$address:~/docker-compose"
    scp "$name/Dockerfile" "$address:~/docker-compose"
    ssh -tt "$address" "cd ~/docker-compose; sudo docker-compose $ACTION"
  fi
done < roster
